server:
  port: 80
spring:
  mail:
    host: smtp.qq.com #腾讯邮件服务器地址
    username: 921119098@qq.com
    password: ylcllsfklqncbdie
    properties:
      mail.smtp.auth: true #必须进行授权认证，它的目的就是阻止他人任意乱发邮件
      mail.smtp.starttls.enable: true #MTP加密方式:连接到一个TLS保护连接
      mail.smtp.starttls.required: true 
      
      
     